<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-03T11:08:38Z" name="Default suite" finished-at="2023-04-03T11:09:08Z" duration-ms="30221">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:fortrainingapp.runners.Runner@6f19ac19]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2023-04-03T11:08:38Z" name="Default test" finished-at="2023-04-03T11:09:08Z" duration-ms="30221">
      <class name="fortrainingapp.runners.Runner">
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:fortrainingapp.runners.Runner@6f19ac19]" started-at="2023-04-03T16:38:38Z" name="setUpClass" finished-at="2023-04-03T16:38:39Z" duration-ms="1024" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:fortrainingapp.runners.Runner@6f19ac19]" started-at="2023-04-03T16:38:39Z" name="feature" description="Runs Cucumber Feature" data-provider="features" finished-at="2023-04-03T16:39:07Z" duration-ms="27747" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Login feature file]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [MY PROJECTSss] but found [MY PROJECTS]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: The following asserts failed:
	expected [MY PROJECTSss] but found [MY PROJECTS]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: The following asserts failed:
	expected [MY PROJECTSss] but found [MY PROJECTS]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at fortrainingapp.stepdefinitions.LoginStepDefinitions.user_should_be_logged_in_successfully(LoginStepDefinitions.java:45)
	at âœ½.Then User should be logged in successfully(LoginFeature.feature:10)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method is-config="true" signature="setup()[pri:0, instance:fortrainingapp.runners.Runner@6f19ac19]" started-at="2023-04-03T16:39:07Z" name="setup" finished-at="2023-04-03T16:39:07Z" duration-ms="62" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:fortrainingapp.runners.Runner@6f19ac19]" started-at="2023-04-03T16:39:07Z" name="tearDownClass" finished-at="2023-04-03T16:39:08Z" duration-ms="1083" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- fortrainingapp.runners.Runner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
